### ISSUE TITLE
[Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by Loganz97** [Gardner-BinfLab/TISIGNER-ReactJS#11]
Keep getting this error when putting in a sequence to TIsigner.

**Comment by lcscs12345** [comment]
Works here. Let us know if this issue still persists.

**Comment by ChrisBrownNZ** [comment]
Him
I am getting the same issue today. It worked fine yesterday.

**Comment by lcscs12345** [comment]
We had doubled the RAM. Our server should be able to cope with more users now.
