### ISSUE TITLE
Tisigner misses 'RNAplfold' when running on localhost / docker build

### ISSUE THREAD

**Issue by ljohn1** [Gardner-BinfLab/TISIGNER-ReactJS#21]
Hello! When I set up the Tisigner web app and run Tisinger on `http://localhost:5050/tisigner`, I end up with following error message:
`[Errno 2] No such file or directory: 'RNAplfold' `
However, SoDoPE, Razor and LazyPair are working fine. Maybe you could please help me out with the dockerfile I used:

```
# Build ViennaRNA
FROM gcc:6.5 AS builder

WORKDIR /app

RUN wget --no-check-certificate https://www.tbi.univie.ac.at/RNA/download/sourcecode/2_4_x/ViennaRNA-2.4.11.tar.gz
RUN tar xf ViennaRNA-2.4.11.tar.gz
RUN cd ViennaRNA-2.4.11 && ./configure && make && make install

# Set up Python and Node
FROM nikolaik/python-nodejs:python3.8-nodejs21-slim AS runtime

WORKDIR /app

RUN apt-get install -y curl

RUN apt-get update
RUN apt-get install -y git gzip wget

ENV NODE_OPTIONS=--openssl-legacy-provider

RUN git clone https://github.com/Gardner-BinfLab/TISIGNER-ReactJS.git .

RUN wget --no-check-certificate https://zenodo.org/records/6071630/files/lazypair_clfs.pickle.gz
RUN gunzip lazypair_clfs.pickle.gz
RUN mv lazypair_clfs.pickle models.pkl
RUN mv models.pkl ./models/scallion/


RUN apt-get install infernal infernal-doc

RUN npm install
RUN npm run build

RUN pip install -r requirements.txt

CMD ["python", "tisigner.py"]
```

Many Thanks!

**Comment by theBNT** [comment]
hi, i was able to reproduce your issue by building the image via
```
docker build -t rnaplfold .
```
then run the container via
```
docker run -it --name rnaplfold-p 5050:5050 rnaplfold
```
then open the project in a browser at `http://localhost:5050/tisigner` and push `Demo Input` and then `Submit`.

It seems that the  `RNAplfold` binary (as referenced in code [here](https://github.com/Gardner-BinfLab/TISIGNER-ReactJS/blob/48967cd5a5ff9fa6296b007fd0e41065617adbff/functions.py#L172)) is missing so you could try to copy the compilation results from the builder over to the runtime image via 
```
COPY --from=builder /usr/local/bin/RNA* /usr/local/bin/
```
before the `CMD` line.
