### ISSUE TITLE
No such file or directory:  TISIGNER-ReactJS/models/scallion/models.pkl

### ISSUE THREAD

**Issue by Gordon5-AI** [Gardner-BinfLab/TISIGNER-ReactJS#7]

**Comment by lcscs12345** [comment]
Hi @Gordon5-AI ,

Thanks for using TISIGNER. Could you please tell us what didn't work for you? I have just tested the example input for LazyPair and it worked.

**Comment by Gordon5-AI** [comment]
> 
Thanks @lcscs12345，
 
This problem occurred when I installed TISIGNER locally. It was caused when I used the `python3 tisigner.py` command, and the model file was missing. Thank you for providing the model download link. Maybe you can add the file to the source code, or explain it in the document.

Thank you very much!

**Comment by lcscs12345** [comment]
Thanks, updated README.
