### ISSUE TITLE
Network Error  Check your internet connection!

### ISSUE THREAD

**Issue by raven44099** [Gardner-BinfLab/TISIGNER-ReactJS#8]
The error persists so I want to report it. I used this page approx. 2 weeks ago and it worked phenomenally. 

Today I tried the standard settings as well as custom, none works. I restarted the computer but no change. 
I switched from our institutional network to my phone's wifi, doesn't help.

Best wishes, 
raven

**Comment by bkb3** [comment]
Hi @raven44099

Apologies. We were doing some server maintenance which caused us to be temporarily offline. But now we are up!

Thanks.

**Comment by raven44099** [comment]
Maybe a different error message would clarify this and supress 'ISSUES' here of this type. Sorry for bothering, I thought you were unaware of this problem.
